_wandb:
    value:
        cli_version: 0.24.0
        e:
            23bn1t3ddj0mjxq18fn3n60nt65dspuj:
                codePath: scripts/train_xgboost.py
                codePathLocal: scripts/train_xgboost.py
                email: Lavanyasrinivas65@gmail.com
                executable: /Users/lavanyasrinivas/Documents/AI-First-Preauth-Fraud-Detection/AI-First-Preauth-Fraud-Detection/.venv/bin/python
                git:
                    commit: efe204c7ac80f4217839e1c373c3a5b4831e2b31
                    remote: https://github.com/LavanyaSrinivas06/AI-First-Preauth-Fraud-Detection.git
                host: MacBookPro
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/lavanyasrinivas/Documents/AI-First-Preauth-Fraud-Detection/AI-First-Preauth-Fraud-Detection/scripts/train_xgboost.py
                python: CPython 3.10.19
                root: /Users/lavanyasrinivas/Documents/AI-First-Preauth-Fraud-Detection/AI-First-Preauth-Fraud-Detection
                startedAt: "2026-01-21T18:00:18.927934Z"
                writerId: 23bn1t3ddj0mjxq18fn3n60nt65dspuj
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 5
                - 6
                - 53
            "2":
                - 5
                - 6
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.19
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
colsample_bytree:
    value: 1
learning_rate:
    value: 0.05
max_depth:
    value: 6
model_type:
    value: XGBoost
n_estimators:
    value: 250
scale_pos_weight:
    value: 1
subsample:
    value: 0.8
used_smote:
    value: true
